### ISSUE TITLE
Initialize Character - Select an armature results in 'NoneType' error 

### ISSUE THREAD

**Issue by chrisphyffer** [vini-guerrero/Godot_Game_Tools#10]
Hello Guys

This is for the `Dev Branch`!

I have two issues from the `Initialize Character` function:

Steps to reproduce:
1.) Load up a blank scene.
2.) Click `Initialize Character`
3.) Select a mixamo character: (I tried both an animated character and a character in TPose Only)

![2](https://user-images.githubusercontent.com/17959437/70982982-d88e9080-206c-11ea-865f-39ebd41790a4.jpg)

**Comment by janne-ha** [comment]
I am not getting this error. Do this happen every time so the current Dev is unusable for you? 
I did notice that my Armature bones didn't get renamed and had to fix it by adding
`            bpy.ops.wm.prepare_mixamo_rig('EXEC_DEFAULT')` 
to line 68 in mixamo_controller.py
![Screenshot from 2019-12-17 13-30-41](https://user-images.githubusercontent.com/58021803/70992139-ad8a5800-20d1-11ea-8c38-1d85b5aa4c91.png)

Im in a rush so hopefully this will fix it for now.

**Comment by chrisphyffer** [comment]
Yeah I get this error every time, so I have to convert to the Master to run some tests
Excellent, I will test this dev branch change in a few days to allow you guys some time to spot more potiential issues. thanks!

**Comment by vini-guerrero** [comment]
Fixed with latest version v2.
