### ISSUE TITLE
Incorect animations

### ISSUE THREAD

**Issue by konstantin890** [vini-guerrero/Godot_Game_Tools#16]
Animations used (contains T-pose fbx): https://drive.google.com/file/d/1UU2CG0hc_18VK7attN3QSEiWu0M7-HLQ/view?usp=sharing
GGT version 2.0
Blender 2.82

To reproduce:
1) Open Blender
1) Initialize Character -> Select T-pose fbx
2) Join Animations ->Select all except T-pose
3) Wait for it to finish then check out the created animations

Additionally, there's some kind of facial animations that I didn't download from Mixamo but somehow appear in the final animations? Not sure where they came from...

**Comment by vini-guerrero** [comment]
It appears that your animation files are different from the source target armature.
The tool assumes you're using animation fbx files from within mixamo as well as same source armature. Therefore, your animations can't match the rig of your T-Pose fbx file.

< Dizzy Idle.fbx | T-Pose.fbx >

![image](https://user-images.githubusercontent.com/18181786/75927751-bc201a00-5e4b-11ea-8c7a-5e4d8fe75a38.png)

**Comment by konstantin890** [comment]
Looks like I somehow downloaded the wrong files lol, sorry for the wasted time...
