### ISSUE TITLE
Blender cannot found script

### ISSUE THREAD

**Issue by TalissonBento** [vini-guerrero/Godot_Game_Tools#17]
**Envrironment**

- Blender 2.8
- Elementary OS 5.1 Hera
- Addons zip Downloaded form master branch

**What happen**
on addons setup, specifically when going to enable the plugin.

**The Error**
after click checkbox (to enable), blender suddenly show the follwing error:

`Traceback (most recent call last):
  File "/home/talisson/blender-2.82-linux64/2.82/scripts/modules/addon_utils.py", line 352, in enable
    mod.__time__ = os.path.getmtime(mod.__file__)
  File "/home/talisson/blender-2.82-linux64/2.82/python/lib/python3.7/genericpath.py", line 55, in getmtime
    return os.stat(filename).st_mtime
FileNotFoundError: [Errno 2] No such file or directory: '/home/talisson/.config/blender/2.82/scripts/addons/godot_game_tools/__init__.py'
`

**The Temporary Solution**
open the terminal and access the Blender's addons folder, then create new folder named `godot_game_tools`, then rename from `godot_game_tools.py` to `__ini__.py` and move it to  `godot_game_tools` folder.

**Comment by vini-guerrero** [comment]
Thanks for the report @TalissonBento , this should be fixed on latest Dev branch. 
(We'll be merging it to master soon as well)
