### ISSUE TITLE
Add a project license

### ISSUE THREAD

**Issue by Calinou** [vini-guerrero/Godot_Game_Tools#21]
The repository currently doesn't seem to contain any license. Could you add one, please? See [Choose a License](https://choosealicense.com/) for more information :slightly_smiling_face:

Note that Blender addons generally choose to use "GPLv2 or later" as a license, since this is the same license as Blender.

**Comment by vini-guerrero** [comment]
Thanks for the heads up on this @Calinou 
Just added it here https://github.com/vini-guerrero/Godot_Game_Tools/blob/master/LICENSE
It's currently only on master, but we have many changes on Dev branch which are under testing before we merge so all branches will have the license file included.
