### ISSUE TITLE
V2.0.5 Texture Baking bakes lighting (And it shouldn't)

### ISSUE THREAD

**Issue by zutils** [vini-guerrero/Godot_Game_Tools#41]
"Create Bake Texture"->"Bake Texture" bakes in the lighting for procedural generated textures. This should not happen as the Godot engine should add the lighting itself.

Furthermore, baking should optionally bake normal maps and specular maps independently.

**Comment by zutils** [comment]
I made the changes myself and sent a pull request.

**Comment by vini-guerrero** [comment]
PR approved.
