### ISSUE TITLE
Feature Request: V2.0.5 When exporting models, temporarily connect image texture instead of procedural texture

### ISSUE THREAD

**Issue by zutils** [vini-guerrero/Godot_Game_Tools#43]
Feature Request: V2.0.5 
This is a 2 in 1 feature request that are very close in nature.

1) Allow exporting of any model instead of just Characters
2) When exporting GLTF via Godot_Game_Tools, the image texture node that is automatically generated via the "Create Bake Texture" button should be automatically, and temporarily, connected to the "Principled BSDF Shader" node. The implications of this are that the gltf model will now be fully ready for importing into Godot with both textures and animations.

**Comment by zutils** [comment]
I made the changes myself and sent a pull request. Please note that this only works with part 2... you still cannot export anything using this system (yet).

**Comment by vini-guerrero** [comment]
Thanks for the PR @zutils , https://github.com/vini-guerrero/Godot_Game_Tools/pull/44 merged now.
