### ISSUE TITLE
Can't enable the add-on, after installing

### ISSUE THREAD

**Issue by TanimSk** [vini-guerrero/Godot_Game_Tools#46]
Hi, 
I am using blender 2.79, 32-bit windows
I have installed the Add-on from file as directed but when enabling, I get this error in **`addon_utils.py`**  _enable_ function
and also in **```_init_.py```**  _GGT_AddonProperties_GGT_ class.<br>
Please help me out. 🙂   <br>
![Capture](https://user-images.githubusercontent.com/67966003/117773671-69fe3400-b25a-11eb-98c2-f8334f2cd696.JPG)

**Comment by vini-guerrero** [comment]
Hello @TanimSk , you can just upgrade your Blender to a version compatible with the add-on. Blender 2.8x or 2.9x will work with no issues.
