### ISSUE TITLE
Renaming an animation sometimes renames the wrong animation.

### ISSUE THREAD

**Issue by HinkelDev** [vini-guerrero/Godot_Game_Tools#9]
Renaming an animation sometimes doesn't rename the currently selected animation but instead renames a different one.

The bug is not always replicable.

**Comment by janne-ha** [comment]
This may be already fixed by @vini-guerrero in latest Dev branch version. Let's keep this open for now and see how it goes.
Big hand for this, keep them coming so we can fix bugs and improve the experience.

**Comment by vini-guerrero** [comment]
Fixed on latest Dev branch.
